name: Publish Python SDK

on:
  push:
    branches:
      - main
    paths:
      - 'python-advisor-core/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
  
      - name: Install dependencies
        working-directory: python-advisor-core
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        working-directory: python-advisor-core
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.SG_PYPI_TOKEN }}
          packages-dir: python-advisor-core/dist/
