name: Publish PHP SDK

on:
  push:
    branches:
      - main
    paths:
      - 'php-advisor-core/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./php-advisor-core

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, intl, json
      
      - name: Validate composer.json
        run: composer validate --strict
      
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress
      
      - name: Notify Packagist
        uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: ${{ secrets.SG_PACKAGIST_USERNAME }}
          api_token: ${{ secrets.SG_PACKAGIST_MAIN_TOKEN }}
