name: Publish .NET SDK

on:
  push:
    branches:
      - main
    paths:
      - 'dotnet-advisor-core/**'

env:
  PACKAGE_DIR: packages

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Generate NuGet package
        working-directory: dotnet-advisor-core
        run: dotnet build --configuration Release -o $PACKAGE_DIR

      - name: Publish NuGet package
        working-directory: dotnet-advisor-core
        env:
          NUGET_SOURCE: ${{ vars.SG_PUBLIC_NUGET_FEED_URL }}
          NUGET_API_KEY: ${{ secrets.SG_PUBLIC_NUGET_FEED_API_KEY }}
        run: dotnet nuget push $PACKAGE_DIR/*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE