name: Publish .NET SDK to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'dotnet-advisor-core/**'

env:
  PACKAGE_DIR: packages
  GITHUB_NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: ${{ env.GITHUB_NUGET_SOURCE }}

      - name: Build project
        working-directory: dotnet-advisor-core
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        working-directory: dotnet-advisor-core
        run: dotnet pack --configuration Release --output $PACKAGE_DIR

      - name: Publish NuGet package to GitHub Packages
        working-directory: dotnet-advisor-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget push $PACKAGE_DIR/*.nupkg --source ${{ env.GITHUB_NUGET_SOURCE }} --api-key $GITHUB_TOKEN --skip-duplicate
